
#UDP_LISTEN_HOST = 'localhost'
UDP_LISTEN_HOST = '127.0.0.1'
UDP_LISTEN_PORT = 5006

HTTP_LISTEN_PORT = 8080

#LOGLEVEL = 'DEBUG'

MISSION_FILENAME = 'CURRENT_MISSION.txt'
GEOFENCE_FILENAME = 'geofence.json'


## SSL stuff:
#SSL_CERT_FILE = ''
#SSL_KEY_FILE = ''

